export enum AppLifecycleState {
  NOT_INITIALIZED = 'NOT_INITIALIZED',
  INITIALIZING = 'INITIALIZING',
  RESTORING_SESSION = 'RESTORING_SESSION',
  LOADING_PROFILE = 'LOADING_PROFILE',
  READY = 'READY',
  ERROR = 'ERROR'
}
